# Generated by Django 5.2.1 on 2025-05-28 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat_type', models.CharField(choices=[('beef', 'Beef'), ('pork', 'Pork'), ('chicken', 'Chicken'), ('lamb', 'Lamb')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('company', models.ForeignKey(limit_choices_to={'role': 'company'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
